version: 2.1

############################################################################

references:
   checkout_job_steps: &checkout_job_steps
      steps:
         - checkout
         - run: 
            name: Checking out dependencies
            command: |
               git clone -b develop --single-branch https://github.com/Zimbra/zm-pkg-tool.git ~/zm-pkg-tool
               git clone -b master --single-branch https://$GITHUB_ACCESS_TOKEN@github.com/Zimbra/zm-nexus.git ~/zm-nexus
               echo "BUILD_NO=$CIRCLE_BUILD_NUM" > config.build
         - persist_to_workspace:
            root: ..
            paths:
               - zm-onlyoffice
               - zm-pkg-tool
               - zm-nexus

   build_job_steps: &build_job_steps
      steps:
         - attach_workspace:
            at: ..
         - run:
            name: Creating build
            command: make -f Makefile.build
            no_output_timeout: 30m
         - store_artifacts:
            path: build/dist
         - persist_to_workspace:
            root: ..
            paths: zm-onlyoffice/build/dist/*

   deploy_s3_job_steps: &deploy_s3_job_steps
      docker:
         - image: 'cimg/python:3.10'
      resource_class: small
      steps:
         - attach_workspace:
            at: ..
         - run:
             name: Create a zip file for artifacts and upload them to the OCI bucket
             command: |
               cd build/dist/
               zip -r $CIRCLE_PROJECT_REPONAME.zip .
               ZIP_FILE_PATH="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM/archives/$CIRCLE_PROJECT_REPONAME.zip"
               curl -X PUT "$OCI_PAR_URL$ZIP_FILE_PATH" -T $CIRCLE_PROJECT_REPONAME.zip
               echo "artifacts uploaded to $ZIP_FILE_PATH"

   publish_packages_job_steps: &publish_packages_job_steps
      steps:
         - attach_workspace:
            at: ..
         - run:
            name: Publish package artifacts to Nexus
            command: |
              sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl
              bash ../zm-nexus/scripts/publish-packages-to-nexus.sh "build/dist"

   std_filters: &std_filters
      filters:
         branches:
            only:
               - master
               - develop
               - zimbra/master

############################################################################

jobs:
   checkout:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:core-ubuntu
      resource_class: small
      <<: *checkout_job_steps

   build_u22:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: $DOCKER_REGISTRY/zm-base-os:devcore-ubuntu-22.04
           auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
      resource_class: small
      <<: *build_job_steps

   build_u20:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-20.04
      resource_class: small
      <<: *build_job_steps

   build_u18:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:devcore-ubuntu-18.04
      resource_class: small
      <<: *build_job_steps

   build_c9:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: $DOCKER_REGISTRY/zm-base-os:devcore-centos-9
           auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
      resource_class: small
      <<: *build_job_steps

   build_c8:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      docker:
         - image: zimbra/zm-base-os:devcore-centos-8
      resource_class: small
      <<: *build_job_steps

   deploy_s3:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      <<: *deploy_s3_job_steps

   publish_packages:
      working_directory: ~/zm-onlyoffice
      shell: /bin/bash -eo pipefail
      circleci_ip_ranges: true
      docker:
      - image: $DOCKER_REGISTRY/zm-base-os:devcore-ubuntu-22.04
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      resource_class: small
      <<: *publish_packages_job_steps

############################################################################

workflows:
   version: 2

   # ----------------------------------------------------------------------------------------
   # only for zimbra/master branch: checkout -> build (all OS) -> publish_packages_to_nexus
   # no manual approval, no S3 deploy
   # ----------------------------------------------------------------------------------------
   zimbra-master-workflow:
      jobs:
         - checkout:
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - build_u22:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - build_u20:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - build_u18:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - build_c9:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - build_c8:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                only: zimbra/master
         - publish_packages:
            context:
               - docker-dev-registry
               - nexus-dev-artifactory
            requires:
               - build_u22
               - build_u20
               - build_u18
               - build_c9
               - build_c8
            filters:
              branches:
                only: zimbra/master

   # ----------------------------------------------------------------------------------
   # all other branches: approval -> checkout -> build -> deploy_s3
   # ----------------------------------------------------------------------------------
   other-branches-workflow:
      jobs:
         - build:
            type: approval
            filters:
              branches:
                ignore: zimbra/master
         - checkout:
            requires:
             - build
            context:
             - docker-dev-registry
            filters:
              branches:
                ignore: zimbra/master
         - build_u22:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                ignore: zimbra/master
         - build_u20:
            requires:
               - checkout
            filters:
              branches:
                ignore: zimbra/master
         - build_u18:
            requires:
               - checkout
            filters:
              branches:
                ignore: zimbra/master
         - build_c9:
            requires:
               - checkout
            context:
               - docker-dev-registry
            filters:
              branches:
                ignore: zimbra/master
         - build_c8:
            requires:
               - checkout
            filters:
              branches:
                ignore: zimbra/master
         - deploy_s3_hold:
            type: approval
            requires:
               - build_u22
               - build_u20
               - build_u18
               - build_c9
               - build_c8
            filters:
              branches:
                ignore: zimbra/master
         - deploy_s3:
            context:
               - oracle
            requires:
               - deploy_s3_hold
            filters:
              branches:
                ignore: zimbra/master
